# Generated by Django 6.0.3 on 2026-04-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='spent_time',
            field=models.IntegerField(default=0, verbose_name='секунды'),
        ),
    ]
