# Generated by Django 6.0.3 on 2026-05-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_todolist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='updates_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
