# Generated by Django 6.0.3 on 2026-05-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_todolist_task_type_subject_todolist_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='task_type',
            field=models.CharField(choices=[('', 'Без типа'), ('homework', 'Домашнее задание'), ('exam', 'Подготовка к экзамену'), ('coursework', 'Курсовая работа'), ('lab', 'Лабораторная работа'), ('self_study', 'Самостоятельное обучение')], default='homework', max_length=50),
        ),
    ]
